In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print('---------')
print(arr.sum(1, keepdims=True))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------
[[10]
 [26]
 [42]]


In [3]:
np.array(arr[:,[1]])

array([[ 2],
       [ 6],
       [10]])

In [4]:
arr.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
np.random.normal(10, 1, (3, 2))

array([[ 9.20554058,  8.86640786],
       [ 9.95822146, 10.7915564 ],
       [10.80064285, 12.48213362]])

In [6]:
arr = np.array([[1,2,3],[4, 5, 6]])
np.pad(arr, ((3,3), (2,0)), constant_values=(10,20))

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10,  1,  2,  3],
       [10, 10,  4,  5,  6],
       [10, 10, 20, 20, 20],
       [10, 10, 20, 20, 20],
       [10, 10, 20, 20, 20]])